"""changed menu_type nullable to True in Restaurants table

Revision ID: 4acec3453e68
Revises: ef5dd785bdde
Create Date: 2024-11-22 14:27:50.290774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acec3453e68'
down_revision = 'ef5dd785bdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('menu_type',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('menu_type',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
