"""made changes in database tables and added a new relationship

Revision ID: 65ff592c016e
Revises: 419c9b054d4e
Create Date: 2024-11-23 10:19:03.805788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ff592c016e'
down_revision = '419c9b054d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('menu_categories_restaurant_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'])
        batch_op.drop_column('restaurant')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('restaurant', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menu_categories_restaurant_fkey', 'restaurants', ['restaurant'], ['id'])
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
