"""made nullable value to True from False in Restaurant table

Revision ID: 81cd5ddbe3a4
Revises: 4acec3453e68
Create Date: 2024-11-22 14:31:06.306079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cd5ddbe3a4'
down_revision = '4acec3453e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('visited',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('visited',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
