"""Added restaurant_profile_image to Restaurants

Revision ID: 87e5fdc575b7
Revises: 81cd5ddbe3a4
Create Date: 2024-11-23 00:37:07.646382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e5fdc575b7'
down_revision = '81cd5ddbe3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_profile_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('restaurant_profile_image')

    # ### end Alembic commands ###
