"""made changes to the dieshes tables

Revision ID: 8bda4d2d094d
Revises: 65ff592c016e
Create Date: 2024-11-23 13:00:14.934167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bda4d2d094d'
down_revision = '65ff592c016e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('dishes_menu_categories_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu_categories', ['menu_category_id'], ['id'])
        batch_op.drop_column('menu_categories_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_categories_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dishes_menu_categories_id_fkey', 'menu_categories', ['menu_categories_id'], ['id'])
        batch_op.drop_column('menu_category_id')

    # ### end Alembic commands ###
